openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:10000
  description: Generated server url
paths:
  /v1/metrics:
    post:
      tags:
      - method-execution-controller
      operationId: save
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddMethodExecutionDto'
        required: true
      responses:
        "201":
          description: Created
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/MethodExecution'
  /v1/metrics/class/{className}/method/{methodName}:
    get:
      tags:
      - method-execution-controller
      summary: Get aggregate execution data by class and method name
      description: "Get aggregate execution data (average, min, max) for a specified\
        \ method of a specified class within a given time range"
      operationId: getExecutionsByClassNameAndMethodName
      parameters:
      - name: className
        in: path
        description: Name of the class
        required: true
        schema:
          type: string
      - name: methodName
        in: path
        description: Name of the method
        required: true
        schema:
          type: string
      - name: startDate
        in: query
        description: Start date for filtering (inclusive)
        required: false
        schema:
          type: string
          format: date-time
      - name: endDate
        in: query
        description: End date for filtering (inclusive)
        required: false
        schema:
          type: string
          format: date-time
      - name: aggregateType
        in: query
        description: Type of aggregation
        required: true
        schema:
          type: string
          enum:
          - total
          - average
          - max
          - min
      responses:
        "200":
          description: Aggregate execution data retrieved successfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ResponseMethodExecutionDto'
        "404":
          description: Invalid request or data not found
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ResponseMethodExecutionDto'
        "500":
          description: Internal server error
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ResponseMethodExecutionDto'
components:
  schemas:
    AddMethodExecutionDto:
      required:
      - className
      - executionTime
      - executionTimestamp
      - methodName
      type: object
      properties:
        className:
          maxLength: 255
          minLength: 0
          type: string
        methodName:
          maxLength: 255
          minLength: 0
          type: string
        executionTime:
          type: integer
          format: int64
        executionTimestamp:
          type: string
          format: date-time
    MethodExecution:
      type: object
      properties:
        id:
          type: integer
          format: int64
        className:
          type: string
        methodName:
          type: string
        executionTime:
          type: integer
          format: int64
        executionTimestamp:
          type: string
          format: date-time
    ResponseMethodExecutionDto:
      type: object
      properties:
        className:
          type: string
        methodName:
          type: string
        aggregateType:
          type: string
          enum:
          - total
          - average
          - max
          - min
        aggregateValue:
          type: number
          format: double
