CREATE TABLE method_execution
(
    id                  BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_name          VARCHAR(255) NOT NULL,
    method_name         VARCHAR(255) NOT NULL,
    execution_time      BIGINT       NOT NULL,
    execution_timestamp TIMESTAMP    NOT NULL
);